### ISSUE TITLE
OpenPose Editor is not working properly

### ISSUE THREAD

**Issue by koaqiu** [fkunn1326/openpose-editor#106]
**Describe the bug**

**To Reproduce**
1. Go to 'openpose editor'
2. Click on 'send to txt2img button'
     or click on 'Detect from Image' button 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/542287/228537305-7b8835ca-7984-4e14-b68f-99d958503d20.png)

**Environment**
 - OS: windows 11
 - Browser chrome 111.0.5563.111

**Additional context**
python: 3.10.6  
•  torch: 1.13.1+cu117  
•  xformers: N/A  
•  gradio: 3.23.0  
•  commit: [955df775](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/955df7751eef11bb7697e2d77f6b8a6226b21e13)  
•  checkpoint: fc2511737a

**Comment by koaqiu** [comment]
![image](https://user-images.githubusercontent.com/542287/228561535-214d2527-62fc-4ad4-8024-b02d7b401f4f.png)

do not exist

"#controlnet > div > div.tabs > div:not(.tab-nav)" 
 "#controlnet > div:nth-child(2) > .tabs > .tabitem, #controlnet > div:nth-child(2) > div:not(.tabs)"

**Comment by koaqiu** [comment]
like this
https://github.com/fkunn1326/openpose-editor/issues/99#issuecomment-1486346829

i change code to

````js
        let input = gradioApp().querySelector(selector).querySelector("#controlnet").querySelector("input[type='file']");
        
        const input_image = (input) =>{
            try {
                if(input.previousElementSibling  
                    && input.previousElementSibling.previousElementSibling 
                    && input.previousElementSibling.previousElementSibling.querySelector("button[aria-label='Clear']")) {
                input.previousElementSibling.previousElementSibling.querySelector("button[aria-label='Clear']").click()
                }
            } catch (e) {
                console.error(e)
            }
            input.value = "";
            input.files = list;
            const event = new Event('change', { 'bubbles': true, "composed": true });
            input.dispatchEvent(event);
        }

        if (input == null){
            const callback = (observer) => {
                input = gradioApp().querySelector(selector).querySelector("#controlnet").querySelector("input[type='file']");
                if (input == null) {
                    console.error('input[type=file] NOT exists')
                    return
                }else{
                    input_image(input)
                    observer.disconnect()
                }
            }
            const observer = new MutationObserver(callback);
            observer.observe(gradioApp().querySelector(selector).querySelector("#controlnet"), { childList: true });
        }else{
            input_image(input)
        }
````
fix

**Comment by fkunn1326** [comment]
@koaqiu Please send me a PR

**Comment by koaqiu** [comment]
> @koaqiu Please send me a PR

done

**Comment by Liz2rdWizard** [comment]
Hey thank you guys for fixing this awesome plugin :) it works now!

Update did not fix it for me on my linux machine, I had to manually remove + reinstall

1. Delete a1111/stable-diffusion-webui/extensions/openpose-editor folder
2. Install the .git manually again
3. Works :+1: 

Thanks!
