### ISSUE TITLE
Detect from image not work

### ISSUE THREAD

**Issue by huoge1** [fkunn1326/openpose-editor#113]
**Describe the bug**
Detect from image not work
To Reproduce
click Detect from image，select a picture，and then error

![1682402677822](https://user-images.githubusercontent.com/45889937/234188117-32bc2d44-87ae-4c24-9c18-897ff568a86a.png)

**Comment by fkunn1326** [comment]
remove stable-diffusion-webui\models\body_pose_model.pth and relaunch will work for you

**Comment by SiuLeeBoss** [comment]
I deleted body_pose_model.pth and restarted, but still got this error

**Comment by Jitone1** [comment]
same here, I reinstall openpose and deleted the file body_pose_model. I restarted and it downloaded the model. Then error.
100%|███████████████████████████████████████████████████████████████████████████████| 200M/200M [00:16<00:00, 12.7MB/s]
Traceback (most recent call last):
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 39
4, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 10
75, in process_api
    result = await self.call_function(
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 88
4, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line
31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.p
y", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.p
y", line 867, in run
    result = context.run(func, *args)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\openpose-editor\scripts\main.py", line
 106, in estimate
    candidate, subset = body_estimation(pil2cv(img))
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\openpose-editor\scripts\openpose\body.
py", line 49, in __call__
    Mconv7_stage6_L1, Mconv7_stage6_L2 = self.model(data)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py
", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\openpose-editor\scripts\openpose\model
.py", line 118, in forward
    out1 = self.model0(x)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py
", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container
.py", line 204, in forward
    input = module(input)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py
", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 319, in lo
ra_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py",
 line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py",
 line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 184, 248] to have 3 channels, but got 4
 channels instead

**Comment by GammelSami** [comment]
I think the 4th channel is the alphachannel.

Workaround: I converted my image to JPEG (which does not support alphachannel), then it worked.

**Comment by fkunn1326** [comment]
I pushed small fix for this issue in https://github.com/fkunn1326/openpose-editor/tree/fkunn1326-patch-3, so please `git switch fkunn1326-patch-3` in this extension's directory.

**Comment by SasukeCOZA** [comment]
I still seem to be getting this problem, did the switch deleted the model, still can't detect from image.

**Comment by mwitz8** [comment]
Has anyone got this working again?
